## Configuration for Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true # For local development. Set to false if you want to use the hostname in a DNS-enabled environment
    hostname: ${HOSTNAME:localhost}

## Configuration for App name and Spring Data
spring:
  application:
    name: microservice
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:37965/railway
    username: root
    password: eGAgdAFCD5AGCcf-fG4F61B1d5bBG2cE
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true

## Instance port
server:
  port: 8080

